import { ROLE_CODE } from 'consts/roles';
import { PATH } from 'consts/urls';

export const redirectionMap: Partial<
  Record<PATH, Partial<Record<ROLE_CODE, PATH>>>
> = {
  [PATH.ROLES]: {
    [ROLE_CODE.NONE]: PATH.ROLES_INBOX,
    [ROLE_CODE.REWARDS]: PATH.ROLES_REWARDS,
    [ROLE_CODE.MANAGER]: PATH.ROLES_MANAGER,
    [ROLE_CODE.REWARDS_AND_MANAGER]: PATH.ROLES_REWARDS,
  },
  [PATH.ROLES_REWARDS]: {
    [ROLE_CODE.NONE]: PATH.ROLES_INBOX,
  },
  [PATH.ROLES_MANAGER]: {
    [ROLE_CODE.NONE]: PATH.ROLES_INBOX,
  },
  [PATH.CREATE]: {
    [ROLE_CODE.REWARDS]: PATH.KEYS_VIEW,
    [ROLE_CODE.MANAGER]: PATH.KEYS_VIEW,
    [ROLE_CODE.REWARDS_AND_MANAGER]: PATH.KEYS_VIEW,
  },
  [PATH.KEYS]: {
    [ROLE_CODE.NONE]: PATH.CREATE,
    [ROLE_CODE.REWARDS]: PATH.KEYS_VIEW,
    [ROLE_CODE.MANAGER]: PATH.KEYS_VIEW,
    [ROLE_CODE.REWARDS_AND_MANAGER]: PATH.KEYS_VIEW,
  },
  [PATH.KEYS_SUBMIT]: {
    [ROLE_CODE.REWARDS]: PATH.KEYS_VIEW,
  },
  [PATH.KEYS_REMOVE]: {
    [ROLE_CODE.REWARDS]: PATH.KEYS_VIEW,
  },
  [PATH.KEYS_EJECT]: {
    [ROLE_CODE.REWARDS]: PATH.KEYS_VIEW,
  },
  [PATH.KEYS_VIEW]: {
    [ROLE_CODE.NONE]: PATH.HOME,
  },
  [PATH.BOND]: {
    [ROLE_CODE.NONE]: PATH.HOME,
    [ROLE_CODE.REWARDS]: PATH.BOND_CLAIM,
    [ROLE_CODE.MANAGER]: PATH.BOND_CLAIM,
    [ROLE_CODE.REWARDS_AND_MANAGER]: PATH.BOND_CLAIM,
  },
  [PATH.BOND_CLAIM]: {
    [ROLE_CODE.NONE]: PATH.HOME,
  },
  [PATH.BOND_ADD]: {
    [ROLE_CODE.NONE]: PATH.HOME,
  },
  [PATH.BOND_UNLOCK]: {
    [ROLE_CODE.NONE]: PATH.HOME,
  },
  [PATH.TYPE]: {
    [ROLE_CODE.NONE]: PATH.HOME,
    [ROLE_CODE.REWARDS]: PATH.TYPE_CLAIM,
    [ROLE_CODE.MANAGER]: PATH.TYPE_CLAIM,
    [ROLE_CODE.REWARDS_AND_MANAGER]: PATH.TYPE_CLAIM,
  },
  [PATH.TYPE_CLAIM]: {
    [ROLE_CODE.NONE]: PATH.HOME,
  },
};
