name: Test CSM-widget
run-name: CSM-widget Tests. Env [${{ github.event.inputs.stand_type || 'testnet' }}]

on:
  schedule:
    - cron: "0 6 * * *" # Every day at 6 AM UTC
  workflow_dispatch:
    inputs:
      stand_type:
        description: "Stand type"
        required: true
        type: choice
        default: testnet
        options:
          - prod
          - staging
          - testnet
          - preview
      tags:
        description: "Tags for running test suite"
        required: false
        type: choice
        default: "-"
        options:
          - "-"
          - smoke
          - performTX
      preview_stand_url:
        description: 'Preview stand url (only if "Stand type" is "preview")'
        required: false
        type: string
      preview_stand_env:
        description: 'Preview stand env (only if "Stand type" is "preview")'
        required: false
        type: choice
        default: testnet
        options:
          - testnet
          - infra

  workflow_call:
    inputs:
      preview_stand_url:
        required: true
        type: string
        description: Stand url
      stand_type:
        description: "Stand type"
        required: true
        type: string
      tags:
        required: false
        type: string
        default: "-"
        description: "Test tags"
      qase_plan_id:
        required: false
        type: number
        description: "Qase Plan ID"

jobs:
  test:
    name: CSM widget
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
    with:
      module: csm
      stand_type: ${{ inputs.stand_type || github.event.inputs.stand_type || 'testnet' }}
      test_tags: ${{ inputs.tags || github.event.inputs.tags || '!forked' }}
      qase_project_id: CSM
      qase_plan_id: ${{ inputs.qase_plan_id || (github.event_name == 'schedule' && '7') || '' }}
      preview_stand_url: ${{ inputs.preview_stand_url || github.event.inputs.preview_stand_url || '' }}
      preview_stand_env: ${{ github.event.inputs.preview_stand_env || '' }}
