import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { format, resolveConfig } from 'prettier';
import * as abis from '@lidofinance/lido-csm-sdk/abi';

const OUT_DIR = 'tests/shared/contracts/abi';
const SOURCE = '@lidofinance/lido-csm-sdk';

const main = async () => {
  const { version } = JSON.parse(
    await readFile(`node_modules/${SOURCE}/package.json`, 'utf8'),
  );
  const banner = `// generated by \`yarn abi:generate\` from ${SOURCE}@${version} — do not edit\n`;
  const prettierConfig = await resolveConfig(join(OUT_DIR, 'index.ts'));
  const write = async (file, code) =>
    writeFile(
      join(OUT_DIR, file),
      await format(banner + code, { ...prettierConfig, parser: 'typescript' }),
    );

  const entries = Object.entries(abis).sort(([a], [b]) => a.localeCompare(b));

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  await Promise.all(
    entries.map(([name, abi]) =>
      write(`${name}.ts`, `export const ${name} = ${JSON.stringify(abi)} as const;`),
    ),
  );

  await write(
    'index.ts',
    entries.map(([name]) => `export { ${name} } from './${name}.ts';`).join('\n'),
  );

  console.info(
    `Generated ${entries.length} ABIs from ${SOURCE}@${version} → ${OUT_DIR}`,
  );
};

void main();
