// generated by `yarn abi:generate` from @lidofinance/lido-csm-sdk@2.3.0 — do not edit
export const AccountingV1EventsAbi = [
  {
    type: 'event',
    name: 'ExpiredBondLockRemoved',
    inputs: [
      {
        name: 'nodeOperatorId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
] as const;
