// generated by `yarn abi:generate` from @lidofinance/lido-csm-sdk@2.3.0 — do not edit
export const VersionCheckAbi = [
  {
    type: 'function',
    name: 'getInitializedVersion',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
] as const;
